rename and clean up code

diff --git a/test_execpdc b/test_execpdc
--- a/test_execpdc
+++ b/test_execpdc
@@ -4,11 +4,11 @@ SAVE=false    # assign true to preserve workdirs
 
 BINDIR=`pwd -P`
 INPUTDIR=$BINDIR/input
-if test -s "$EXECPDC_JOBE_RUNS"
-then cd "$EXECPDC_JOBE_RUNS"
-else eval `grep -m 1 JOBE_RUNS execpdc.config || echo false` &&
-	cd $JOBE_RUNS || {
-	    echo "JOBE_RUNS not defined in execpdc.config, aborting"
+if test -s "$EXECPDC_JOBE_DIR"
+then cd "$EXECPDC_JOBE_DIR"
+else eval `grep -m 1 JOBE_DIR execpdc.config || echo false` &&
+	cd $JOBE_DIR || {
+	    echo "JOBE_DIR not defined in execpdc.config, aborting"
 	    exit 1
 	}
 fi
